name: Release Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and publish Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/my-image:${{ github.sha }} .
          docker push docker.pkg.github.com/${{ github.repository }}/my-image:${{ github.sha }}
